#pragma once

#include "impl/ops/dispatch.hpp"

#if !defined(TSIMD_DISPATCH_THIS_FILE)
    #error "has not defined TSIMD_DISPATCH_THIS_FILE"
#endif


#undef TSIMD_ONCE
#define TSIMD_ONCE 0


// AVX512_F
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION AVX512_F
// 此时 TSIMD_DYN_FUNC_ATTR 等于 AVX512_F
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_AVX512_F_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch


// AVX2_FMA3
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION AVX2_FMA3
// 此时 TSIMD_DYN_FUNC_ATTR 等于 AVX2_FMA3
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_AVX2_FMA3_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch


// AVX2
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION AVX2
// 此时 TSIMD_DYN_FUNC_ATTR 等于 AVX2
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_AVX2_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch


// AVX
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION AVX
// 此时 TSIMD_DYN_FUNC_ATTR 等于 AVX
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_AVX_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch



// SSE2
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION SSE2
// 此时 TSIMD_DYN_FUNC_ATTR 等于 SSE2
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_SSE2_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch



// SSE
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION SSE
// 此时 TSIMD_DYN_FUNC_ATTR 等于 SSE
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_SSE_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch



// last dispatch
#undef TSIMD_DETAIL_LAST_DISPATCH
#define TSIMD_DETAIL_LAST_DISPATCH 1

// Scalar
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION Scalar
// 此时 TSIMD_DYN_FUNC_ATTR 等于 Scalar
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_SCALAR_INTRINSIC_ATTR
// #include TSIMD_DISPATCH_THIS_FILE // dispatch (不需要include)


// once
#undef TSIMD_ONCE
#define TSIMD_ONCE 1



#undef TSIMD_DISPATCH_THIS_FILE
