#pragma once

#include "impl/ops/dispatch.hpp"

#if !defined(TSIMD_DISPATCH_THIS_FILE)
    #error "has not defined TSIMD_DISPATCH_THIS_FILE"
#endif

#define TSIMD_DETAIL_LAST_DISPATCH 0

#undef TSIMD_ONCE
#define TSIMD_ONCE 0


// AVX
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION AVX
// 此时 TSIMD_DYN_FUNC_ATTR 等于 AVX
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_AVX_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch



// SSE2
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION SSE2
// 此时 TSIMD_DYN_FUNC_ATTR 等于 SSE2
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_SSE2_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch



// SSE
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION SSE
// 此时 TSIMD_DYN_FUNC_ATTR 等于 SSE
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR TSIMD_SSE_INTRINSIC_ATTR
#include TSIMD_DISPATCH_THIS_FILE // dispatch



// last dispatch
#undef TSIMD_DETAIL_LAST_DISPATCH
#define TSIMD_DETAIL_LAST_DISPATCH 1

// Scalar
#undef TSIMD_DYN_INSTRUCTION
#define TSIMD_DYN_INSTRUCTION Scalar
// 此时 TSIMD_DYN_FUNC_ATTR 被清空
#undef TSIMD_DYN_FUNC_ATTR
#define TSIMD_DYN_FUNC_ATTR
// #include TSIMD_DISPATCH_THIS_FILE // dispatch (不需要include)


// once
#if TSIMD_DETAIL_LAST_DISPATCH
    #undef TSIMD_ONCE
    #define TSIMD_ONCE 1
#endif



#undef TSIMD_DISPATCH_THIS_FILE
