#pragma once

#include "../math_defs.hpp"

#define TMATH_COMPILE_TIME_NAMESPACE_NAME TMATH_NAMESPACE_NAME::CompileTime
#define TMATH_COMPILE_TIME_NAMESPACE_BEGIN namespace TMATH_COMPILE_TIME_NAMESPACE_NAME {
#define TMATH_COMPILE_TIME_NAMESPACE_END }
