#pragma once

#include "../platform.hpp"

// scalar
#define TSIMD_SCALAR_INTRINSIC_ATTR
#define TSIMD_OP_SCALAR_API \
    TSIMD_FORCE_INLINE \
    TSIMD_FLATTEN \
    TSIMD_SCALAR_INTRINSIC_ATTR


// sse
#define TSIMD_SSE_INTRINSIC_ATTR TSIMD_FUNC_ATTR_INTRINSIC_TARGETS("sse")
#define TSIMD_OP_SSE_API \
    TSIMD_FORCE_INLINE \
    TSIMD_FLATTEN \
    TSIMD_SSE_INTRINSIC_ATTR


// sse2
#define TSIMD_SSE2_INTRINSIC_ATTR TSIMD_FUNC_ATTR_INTRINSIC_TARGETS("sse2")
#define TSIMD_OP_SSE2_API \
    TSIMD_FORCE_INLINE \
    TSIMD_FLATTEN \
    TSIMD_SSE2_INTRINSIC_ATTR



// sse3

// sse4.1



// avx(no fma3)
#define TSIMD_AVX_INTRINSIC_ATTR TSIMD_FUNC_ATTR_INTRINSIC_TARGETS("avx")
#define TSIMD_OP_AVX_API \
    TSIMD_FORCE_INLINE \
    TSIMD_FLATTEN \
    TSIMD_AVX_INTRINSIC_ATTR


// avx2

// avx2+fma3

// avx512
